### ISSUE TITLE
virtio-serial-bus: Unexpected port id 2909357808 for device virtio-serial0.0

### ISSUE THREAD

**Issue by yangni2017** [virtio-win/kvm-guest-drivers-windows#1252]
**Describe the bug**
qemu give the error log "qemu-system-x86_64: virtio-serial-bus: Unexpected port id 2909357808 for device virtio-serial0.0"
i found redhat virtio-win [[Bug 819412](https://bugzilla.redhat.com/show_bug.cgi?id=819412)](https://bugzilla.redhat.com/show_bug.cgi?id=819412) ，There are similar issues and they seem to have been resolved, is there a synchronous solution here？

**To Reproduce**
Steps to reproduce the behaviour:
My server has more than a dozen Windows virtual machines, and two of them often have this problem. There is no special operation.

**Host:**
 - Disto: [centos8]
 - Kernel version : 5.10.0
 - QEMU version: 6.2.0
 - QEMU command line:
```
 /usr/bin/qemu-system-x86_64 -name guest=GDT7767733d-07e5-4850-8126-7b24df71d9da,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-6-GDT7767733d-07e5-485/master-key.aes"} -machine pc-i440fx-6.2,accel=kvm,usb=off,dump-guest-core=off -cpu Broadwell-IBRS,vmx=off,mpx=off,hv-time,kvm-pv-eoi=on,hv-relaxed,hv-vapic,hv-spinlocks=0x1fff -m size=8388608k,slots=64,maxmem=536870912k -overcommit mem-lock=off -smp 8,sockets=2,dies=1,cores=4,threads=1 -object {"qom-type":"memory-backend-ram","id":"ram-node0","size":4294967296} -numa node,nodeid=0,cpus=0-3,memdev=ram-node0 -object {"qom-type":"memory-backend-ram","id":"ram-node1","size":4294967296} -numa node,nodeid=1,cpus=4-7,memdev=ram-node1 -uuid 7767733d-07e5-4850-8126-7b24df71d9da -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=40,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device pci-bridge,chassis_nr=1,id=pci.1,bus=pci.0,addr=0x3 -device pci-bridge,chassis_nr=2,id=pci.2,bus=pci.0,addr=0x4 -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device nec-usb-xhci,id=usb1,bus=pci.0,addr=0x9 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x7 -device ahci,id=sata0,bus=pci.0,addr=0x8 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0xa -global isa-fdc.bootindexA=3 -device ide-cd,bus=ide.1,unit=1,id=ide0-1-1,bootindex=2 -device floppy,unit=0,id=fdc0-0-0 -blockdev {"driver":"iscsi","portal":"10.30.9.18:20918","target":"iqn.2018-11.xxx.com.cn:9e7eb154-b627-4291-9fee-41090ffbc727id166057559","lun":1,"transport":"tcp","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -device ide-hd,bus=sata0.0,drive=libvirt-2-format,id=sata0-0-0,bootindex=4,write-cache=on -blockdev {"driver":"iscsi","portal":"10.30.9.18:20559","target":"iqn.2018-11.xxx.com.cn:77b6daaf-f0bd-48e0-81ea-77c825443d24id96054217","lun":1,"transport":"tcp","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-1-storage"} -device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=1,device_id=T001-81ea77c825443d24,drive=libvirt-1-format,id=scsi0-0-0-1,bootindex=5,wwn=0x65254ffff0bd48e0,write-cache=on,serial=T001-81ea77c825443d24 -netdev tap,fd=43,id=hostnet0,vhost=on,vhostfd=44 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:56:ff:da:4f:32,bus=pci.0,addr=0x5 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev pty,id=charserial1 -device isa-serial,chardev=charserial1,id=serial1 -chardev socket,id=charchannel0,fd=45,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 -chardev socket,id=charchannel1,fd=46,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charchannel1,id=channel1,name=org.qemu.client_guest_tool.0 -chardev socket,id=charchannel2,fd=47,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=3,chardev=charchannel2,id=channel2,name=org.qemu.client_guest_tool.1 -chardev socket,id=charchannel3,fd=48,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=4,chardev=charchannel3,id=channel3,name=topsec_clip_board.0 -chardev socket,id=charchannel4,fd=49,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=5,chardev=charchannel4,id=channel4,name=topsec_clip_board.1 -chardev socket,id=charchannel5,fd=50,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=6,chardev=charchannel5,id=channel5,name=topsec_shared_dir.0 -chardev socket,id=charchannel6,fd=51,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=7,chardev=charchannel6,id=channel6,name=topsec_shared_dir.1 -chardev socket,id=charchannel7,fd=52,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=8,chardev=charchannel7,id=channel7,name=topsec_shared_file.0 -chardev socket,id=charchannel8,fd=53,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=9,chardev=charchannel8,id=channel8,name=topsec_shared_file.1 -chardev socket,id=charchannel9,fd=54,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=10,chardev=charchannel9,id=channel9,name=topsec_network_printer.1 -chardev socket,id=charchannel10,fd=55,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=11,chardev=charchannel10,id=channel10,name=topsec_network_printer.0 -chardev socket,id=charchannel11,fd=56,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=12,chardev=charchannel11,id=channel11,name=topsec_smb_path.0 -chardev spicevmc,id=charchannel12,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=13,chardev=charchannel12,id=channel12,name=com.redhat.spice.0 -chardev spiceport,id=charchannel13,name=org.spice-space.webdav.0 -device virtserialport,bus=virtio-serial0.0,nr=14,chardev=charchannel13,id=channel13,name=org.spice-space.webdav.0 -chardev spiceport,id=charchannel14,name=org.topsec.raw.0 -device virtserialport,bus=virtio-serial0.0,nr=15,chardev=charchannel14,id=channel14,name=org.topsec.raw.0 -chardev pty,id=charconsole1 -device virtconsole,chardev=charconsole1,id=console1 -device usb-tablet,id=input1,bus=usb.0,port=1 -spice port=5906,addr=::0.0.0.0,image-compression=glz,jpeg-wan-compression=always,streaming-video=filter,seamless-migration=on -device qxl-vga,id=video0,ram_size=134217728,vram_size=67108864,vram64_size_mb=0,vgamem_mb=32,max_outputs=1,bus=pci.0,addr=0x2 -device intel-hda,id=sound0,bus=pci.0,addr=0x6 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb1.0,port=1 -chardev spicevmc,id=charredir2,name=usbredir -device usb-redir,chardev=charredir2,id=redir2,bus=usb1.0,port=2 -chardev spicevmc,id=charredir3,name=usbredir -device usb-redir,chardev=charredir3,id=redir3,bus=usb1.0,port=3 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0xb -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -device pvpanic -msg timestamp=on
```
 - libvirt version: 6.2.0

**VM:**
 - win10

**Comment by YanVugenfirer** [comment]
@yangni2017 What driver version are you using?

Can you describe the steps that lead to the problem?

**Comment by yangni2017** [comment]
the driver we get from [spice-guest-tools](https://spice-space.org/download/windows/spice-guest-tools/) , and use the latest, but the lastest pack is 2018.

There are no special steps. Just start  the qemu  and connect to the spice console normally. After using it for a while, some virtual machines will have this kind of printing. It will appear every time you click the mouse or copy text, because we have a clipboard channel. After reboot vm, it recovery

**Comment by YanVugenfirer** [comment]
I suggest to update the driver. You might be using the driver with the bug described by bugzilla and it was already fixed

**Comment by yangni2017** [comment]
> I suggest to update the driver. You might be using the driver with the bug described by bugzilla and it was already fixed

Can you tell me how this bug affects the use of the channel? Because sometimes the print still exists when everything seems to be working fine. I am not sure if my spice mouse anomaly is related to this bug, but after I reconnected spice the mouse returned to normal but the error print still exists

**Comment by yangni2017** [comment]
> I suggest to update the driver. You might be using the driver with the bug described by bugzilla and it was already fixed

ok.thanks you  very much. I try to update the driver. I will give you feedback in time when there are test results. Can i get the lastest driver from [](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md)  ?

**Comment by YanVugenfirer** [comment]
@yangni2017 Try here: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.266-1/
