### ISSUE TITLE
[vioscsi] - Reset to device \Device\Raidport1\ was issued - system unresponsive.

### ISSUE THREAD

**Issue by casper** [virtio-win/kvm-guest-drivers-windows#623]
I'm running vioscsi on a Windows 2012 R2 Hetzner CPX11 Cloud instance (AMD EPYC). 

There is a very strange issue at random intervals (hour, to days, and sometimes weeks, but usually with heavy/heavier disk activity), I get a "Reset to device \Device\Raidport1\ was issued", Event ID 129 in the event log.

When this happens whatever process was responsible for triggering this event freezes, and there is no way to kill that process or get rid of it through task manager or any other method that I tried. Even rebooting does not help, as the system refuses to reboot because of this stuck process when this issue hits.

The only way to get the VM working properly again is a hard power cycle.

I've tried all the tips and tricks I could find on the net in order to resolve this issue. Fiddling with the Windows Advanced Power Settings, change AHCI settings, PCI Express Link State Power management, even changing some registry values related to power management. Disabled all sleep from everything. Disabled HD drive caching in device manager. Nothing seems to help.

I've also copied my VM image to another server, to make sure it was not caused by a particular VM instance. Did not help either.

Does anyone know what could be causing this? Is there some way I could debug it further, or any tips on how to get around it? 

Thanks.

**Comment by vrozenfe** [comment]
@casper 
Event 129 means IO timeout. Usually happens if SCSI Target  doesn't return response after certont amount of time (30 sec by default IIRC). What is your storage backend? Is is a local disk/file of SAN/iSCSI target?

Best,
Vadim.

**Comment by casper** [comment]
The disks are local NVMe SSD drives with RAID. That is what Hetzner says at the VM checkout page.

"Servers with local disks keep all data on a local RAID mirror on the host system. They are optimized for high I/O performance and low latency and are especially suited for applications which require fast access to disks with low latency, such as databases."

I also tried moving the VM to a different physical server, to make sure it was not a local server problem, but I got the same issue still.

**Comment by vrozenfe** [comment]
you can try adjust TimeoutValue
https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/registry-entries-for-scsi-miniport-drivers

or IoTimeoutValue
https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/registry-entries-for-storport-miniport-drivers

in the Windows Registry. 

I would also suggests to confirm with your provider, that they actually provide a dedicated physical storage for you VM.
If you want, I can take a look at your VM system event log file. Just ping  me at vrozenfe_at_redhat_dot_com  

Regards,
Vadim.

**Comment by casper** [comment]
Awesome. Thanks a lot @vrozenfe . I will try to adjust the timeouts and get back to you. I just had another freeze today. Going to try to change those settings now.

**Comment by casper** [comment]
I had it freeze again even with the new timeout settings. I sent you an email with the event log. Pinging you here in case the email goes to your spam folder.

**Comment by casper** [comment]
Update for anyone else running into the same problem: 
Switching from AMD EPYC to the Intel-based servers on Hetzner seems to fix the issue. Now running for 3 weeks without a freeze. They cost a bit more, but it beats constantly having to reboot.

**Comment by YanVugenfirer** [comment]
> Update for anyone else running into the same problem:
> Switching from AMD EPYC to the Intel-based servers on Hetzner seems to fix the issue. Now running for 3 weeks without a freeze. They cost a bit more, but it beats constantly having to reboot.

Closing based on this comment.

**Comment by mherlitzius** [comment]
Unfortunately we are experiencing exactly the same issue. This happened already several times. VM is frozen, only cold reboot helps.

**Environment:**
- KVM / libvirt 3.0.0-4+deb9u5
- Storage: Ceph Nautilus 14.2.21, SSD pool
- Problem occurs on both Intel (Xeon E5-2643) and AMD (EPYC 7F72) compute nodes

**Affected VMs:**
Windows server version: Windows Server 2016
- Virtio driver version: 100.77.104.17100
- Balloon driver version: 100.77.104.17100

Windows server version: Windows Server 2012 R2
- Virtio driver version: 62.74.104.14100
- Balloon driver version: 62.74.104.14100

It seems only / primarily servers running MS SQL Server are affected.

The error message means that the storage does not respond for 30 seconds. In Ceph we see nothing close to that, latency of the affected volume is good. Disk performance and throughput on the Ceph SSD storage pool is excellent when measured with CrystalDiskMark.

On a volume on which this error occured once, we can reproduce it as follows:
- run CrystalDiskMark on that volume (or just copy files from that volume), while the volume is attached to the original server. The error appears in the log and the VM freezes within seconds.

When we can not reproduce this issue:
- If the affected volume is attached to another VM, we can not reproduce this problem. Running the same operation (e.g. CrystalDiskMark or copying files) on the same volume when attached to another VM the error does not occur.
- Running the same operation on a (newly created) volume on the initial VM does not reproduce the problem.

This means that apparently "only" this combination of volume and VM causes the problem.

We have been able to resolve this issue at least for some time, by copying the data from the affected volume to a new volume (while attached to another VM) and then attach the newly created volume to the initial VM.

It is working for a while before the error reoccurs.

It also seems that after the problem occurred for the very first time on a volume it then reoccurs more often (it is not always possible to immediately replace the affected volume as described above).

Do you have any idea what could be causing this problem and how we can work around it? Thank you very much.

**Comment by vrozenfe** [comment]
Hopefully, the problem has been fixed for both vioscsi and viostor with https://github.com/virtio-win/kvm-guest-drivers-windows/pull/684 and https://github.com/virtio-win/kvm-guest-drivers-windows/pull/683 commits respectively. 

Vadim.

**Comment by ylluminate** [comment]
Still experiencing this kind of problem. This followed an upgrade from the 0.1.204-1 drivers (which worked without issue) to the 0.1.217-2 drivers.

Windows Logs → System:
```
Source: vioscsi
Event ID: 129
Level: Warning
Message: Reset to device, \Device\RaidPort2, was issued.
```
This results in the virtual machine guest being entirely unresponsive even to direct console attachment and having to force stop/start the Windows guest.

**Comment by ylluminate** [comment]
Any reason this hasn't received any direct attention so far? It's really creating some trouble for a lot of folks who aren't familiar with this situation.

**Comment by vrozenfe** [comment]
There is a good chance that the problem is not in the vioscsi driver at all. 
Event 129 is just an indication that a request was not completed in time and the system is 
asking miniport driver to cancel andcomplete all outstanding requests. 
If such problem happens occasionally, then  https://github.com/virtio-win/kvm-guest-drivers-windows/pull/684 should be able to handle this situation. Hoverer, if the problem is persistent and happens at the storage subsystem level (https://bugzilla.redhat.com/show_bug.cgi?id=1973317 as an example) then vioscsi driver has nothing to do with that.
We went through the very intensive testing of https://github.com/virtio-win/kvm-guest-drivers-windows/pull/684 and https://github.com/virtio-win/kvm-guest-drivers-windows/pull/683 patches,  emulating the storage subsystem errors and delays  
on different setups. As for now a storage subsystem malfunction seems to be the only reason for getting events 129 and153

**Comment by ylluminate** [comment]
@vrozenfe the one thing I can guarantee is that something following the `0.1.204-1` driver set broke the system to the point where this consistently occurs. I would be happy to help trace it down, but even `virtio-win-0.1.221-1` still results in the same impassable problem.

**Comment by vrozenfe** [comment]
@ylluminate 
Can you please share the system event log file ?
Please ping me at vrozenfe at redhat dot com if you need any help with that.
All the best,
Vadim.

**Comment by mherlitzius** [comment]
To address this issue, we migrated affected VMs to compute nodes with local storage.

**Comment by vrozenfe** [comment]
@mherlitzius 
That makes a lot of sense. 
We do observe storage related issues on network connected storages.
But I've never seen any serious problem on local storage. 

Best,
Vadim.

**Comment by ylluminate** [comment]
@vrozenfe sent - thanks.

**Comment by sub205** [comment]
We are also experiencing this kind of problem with a w2019 running exchange and drivers 0.1.221.
Storage is a local ZFS RAID10 with SSDs.
No errors in the hypervisor syslog.
Error 129 occures during high I/O-load (backup of other VMs on the same hypervisor) but ONLY for this exchange VM (which does not do anything special during the evening)

**Comment by sub205** [comment]
@vrozenfe: The system gets sluggish, sometimes it bluescreens and the exchange db gets corrupted badly.
The problem appeared somewhere the last weeks, maybe due to a Windows update. But only on the exchange server, all other VMs run fine.

I had a bit of rush to get it fixed, so i switched to virtio scsi single AND downgraded to virtio-drivers 204. Problem disappeared since then.

Another interesting fact is, that this happened during the backup of other VMs was running on the same hypervisor. 

System is running Proxmox.

**Comment by szekerest** [comment]
Same issue here (proxmox + Win10 guest).
Downgrading to virtio-drivers 204 seems to "solve" the problem.

**Comment by grayguest** [comment]
@sub205 @szekerest Hello sir, How to degrade to version 204?

**Comment by sub205** [comment]
@grayguest 
1) go to https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/
2) download corresponding .iso
3) insert iso into vm
4) device manager -> update driver -> select from virtual cd.

**Comment by grayguest** [comment]
Has downgraded to v204, also have the problem, so sad.

**Comment by sub205** [comment]
Is your problem the disk IO error or something similar? What virtualisation are you running?
I know of a kernel-bug related to qemu/kvm which was fixed lately. (freezing VM with 100% cpu load)

**Comment by grayguest** [comment]
> Is your problem the disk IO error or something similar? What virtualisation are you running? I know of a kernel-bug related to qemu/kvm which was fixed lately. (freezing VM with 100% cpu load)

I currently changed the disk type from SCSI to SATA, and changed the SCSI controller to the default PVE default (LSI 53C895A), so there should be no vioscsi-related errors because the relevant drivers are not installed.

**Comment by ylluminate** [comment]
Any news @vrozenfe?

**Comment by vrozenfe** [comment]
Unfortunately, I don't have any updates on this issue.

As far as I know we don't have such problems reported by our RHEL or CNV customers. 
Our QE also was not able to reproduce this problem, except for very specific scenario 
reported at https://issues.redhat.com/browse/RHEL-1609

During the developing and testing cycle we emulated the situation when a SCSI request  is 
completely lost by the SCSI target. In this case the driver is capable of handling the reset 
request and complete all pending SCSI requests.  
Normally the bus reset request (event ID 129) is initiated if a SCSI request is not completed after 
60 seconds (or any other time specified as a miniport IoTimeOutValue Registry parameter). While 
this logic works quite well for the most of the cases there is still at least one condition when the 
entire logic probably doesn't work  when a SCSI request that is considered to be "lost" and completed
 is coming back  to the virtio driver. Normally, this situation should be handled by increasing the 
SRB TimeOutValue which is corresponded to the Registry IoTimeOutValue parameter mentioned above. 

I cannot give you any suggestion regarding this Registry key value. Technically it can be set up to  65535 
seconds ( https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/registry-entries-for-storport-miniport-drivers ) but I definitely can not suggest increasing this value to more then 250. As for me, even the 
default value in 60 seconds is a huge amount of time, but I have to say that we have seen that in some 
cases this time can be exceeded. Another solution can be to try limiting the maximum transfer size reported 
by the miniport driver. 
If I understand correctly, most of the cases happen on the Proxmox virtualization platforms. I personally have no connections with any of the technical staff members working for this company. But if any of them is reading this thread, please feel free to ping me at vrozenfe_at_redhat_dot_com to discuss this issue.

Best,
Vadim.

**Comment by grayguest** [comment]
> Another solution can be to try limiting the maximum transfer size reported by the miniport driver. 

@vrozenfe Sir, Does this mean that the network card sending/receiving rate or the packet length is too large, will it also cause this problem?

**Comment by ylluminate** [comment]
Given the state of affairs and news with the Broadcom VMware acquisition @vrozenfe, it appears that options such as Proxmox are going to be much more heavily and widely adopted, so it would be good to get more details in this area.

**Comment by ylluminate** [comment]
Request to Proxmox folks made: https://forum.proxmox.com/threads/redhat-virtio-developers-would-like-to-coordinate-with-proxmox-devs-re-vioscsi-reset-to-device-system-unresponsive.139160/#post-621403

**Comment by devZer0** [comment]
also mind/don't forget that unfortunate qemu configuration defaults may led to freeze/hickup of virtual machines.   most of my problems with freeze or vm stuttering went away after making sure, every VM is using virtio dataplane (= virtio-scsi-single + iothread )  , see https://bugzilla.kernel.org/show_bug.cgi?id=199727#c8

**Comment by vrozenfe** [comment]
@grayguest 
vioscsi is capable to handle up to 2MB DMA/transfer in one go  (512 * 4KB  https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/vioscsi/vioscsi.h#L53C15-L53C15) and some application like SQL or backup utilities can use such size of IO. It should work fine on top of direct LUN presented by SSD or NVMe disk, but when it comes to the network storage I cannot say the same for sure. I have seen 64KB transfer taking 4 seconds to be completed. So it can be that 2MB takes more than 60  seconds. In this situation the solution can be to increase IoTimeOutValue or to decrease the maximum transfer size by  adding 'max_srctors=32" to the virtio-scsi device parameters in the QEMU command line or adding "PhysicalBreaks" parameter to the Registry (https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/vioscsi/vioscsi.c#L486)

Best,
Vadim.

**Comment by foxmox** [comment]
Hi,
Proxmox developer here.

> During the developing and testing cycle we emulated the situation when a SCSI request  is completely lost by the SCSI target. In this case the driver is capable of handling the reset request and complete all pending SCSI requests.  Normally the bus reset request (event ID 129) is initiated if a SCSI request is not completed after 60 seconds (or any other time specified as a miniport IoTimeOutValue Registry parameter). While this logic works quite well for the most of the cases there is still at least one condition when the entire logic probably doesn't work  when a SCSI request that is considered to be "lost" and completed is coming back  to the virtio driver. Normally, this situation should be handled by increasing the SRB TimeOutValue which is corresponded to the Registry IoTimeOutValue parameter mentioned above.
> 
> I cannot give you any suggestion regarding this Registry key value. Technically it can be set up to  65535  seconds ( https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/registry-entries-for-storport-miniport-drivers ) but I definitely can not suggest increasing this value to more then 250. As for me, even the default value in 60 seconds is a huge amount of time, but I have to say that we have seen that in some cases this time can be exceeded. Another solution can be to try limiting the maximum transfer size reported by the miniport driver.  If I understand correctly, most of the cases happen on the Proxmox virtualization platforms. I personally have no connections with any of the technical staff members working for this company. But if any of them is reading this thread, please feel free to ping me at vrozenfe_at_redhat_dot_com to discuss this issue.
> 

Thank you for the explanation and suggesting a workaround! The situation where a request takes more than 60 seconds and later completes successfully is possible in combination with QEMU's backup block job and our custom network backup target (PBS). It might be that users schedule more concurrent backups to PBS than their hardware can easily handle. And with the copy-before-write mechanism used by the backup block job, guest IO will be limited by that.

I think I am able to reproduce the issue by simply cutting the connection to the backup target for two minutes during backup. It will later complete successfully, but afterwards in the guest, there will be an vioscsi error event with ID 129 (sometimes multiple ones afterwards, one every minute).

Could the logic be fixed to deal with such late successful requests? While the reports indicate that the issue only happens in combination with the Proxmox VE backup mechanism, there could be other (future) scenarios. Or should we just suggest the workaround to affected users (and to reduce the load on their backup target)?

I am aware that there is the possibility with QEMU to do image fleecing nowadays and also abort a backup if a copy-before-write operation hits a given timeout (`cbw-timeout`+`on-cbw-error=break-snapshot` options). Those should also work around the issue, but we haven't gotten around to implementing those yet.

Best Regards,
Fiona

**Comment by vrozenfe** [comment]
Hi Fiona,
Glad to get in touch with you. 
We do trying to reset HBA as a part of the hierarchical SCSI Bus rest handler
https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/vioscsi/vioscsi.c#L1443
The logic here based on assumption that a request submitter to QEMU and not complied in time is lost or cleaned by the storage backend and will never come back to guest. 
Let me check if there is any way to make this logic working better,

Best,
Vadim.

**Comment by Sage222** [comment]
i was having this issue every few minutes on windows 11 when passing through my onboard sata to the VM in proxmox.  I stopped passing through the onboard sata and changed to passing through the invidual drives and that fixed it for me.
